### ISSUE TITLE
cannot see the catalog added in brooklyn

### ISSUE THREAD

**Issue by niekun** [cloudfoundry-attic/apache-brooklyn-service-broker#31]
Ｈｉ
I deploy the version 0.10 broker and brooklyn 0.10.
Then added below catalog by using brooklyn GUI
```yaml
brooklyn.catalog:
    id: mysql
    version: 1.0
    iconUrl: classpath://mysql.png
    description: MySql is an open source relational database management system (RDBMS)
name: MySQL Database
services:
- type: brooklyn.entity.basic.BasicApplication
  brooklyn.children:
    - type: brooklyn.entity.database.mysql.MySqlNode
      id: mysql
      name: MySQL Node
```
After that I update the service broker by using below command:
```sh
 cf update-service-broker brooklyn broker-username broker-password https://brooklyn-service-broker.cf.hkdaac.com
```
But I　can only got below result by running  cf service-access
```sh
ubuntu@bosh-orch:~/brooklyn_broker$ cf service-access
Getting service access as admin...
broker: brooklyn
   service                        plan      access   orgs
   br_apache_brooklyn_blueprint   default   none
```
Do you have any idea on it?
